# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://vagrant.corp.anjuke.com/boxes/precise32.box"
  config.vm.network :hostonly, "172.20.100.155"

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
#    ansible.inventory_file = "provisioning/ansible_hosts"
    ansible.verbose = true
  end
end
